name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            ./requirements/base.txt
            ./requirements/dev.txt
      
      - name: Install dependencies
        working-directory: ./requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r base.txt
          pip install -r dev.txt
      
      - name: Run linter
        run: |
          flake8 .
      
      - name: Run tests
        run: |
          pytest